### ISSUE TITLE
where is .ckpt file?Thanks

### ISSUE THREAD

**Issue by xjadolphx** [lewisluk/BoundaryAwareNetwork#2]
Would you please tell me where to find the checkpoint or ckpt file？Or is should i obtain it through extra steps?

Anyway, thank you all the same for your code !

**Comment by lewisluk** [comment]
> Would you please tell me where to find the checkpoint or ckpt file？Or is should i obtain it through extra steps?
> 
> Anyway, thank you all the same for your code !

I haven't got the result mentioned in their paper, so there are no trustworthy ckpt files.
Sorry about that.

**Comment by xjadolphx** [comment]
Thanks！
